### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by wwyy1234** [damo-cv/MotionRGBD#6]
不好意思，前段时间因为跑不出准确率打扰了您一段时间，然而我之后按着您的数据采样方法来跑nvgesture数据集，仍然跑不到您的准确率，差10个点左右，遂放弃了一段时间。不过昨天与一个学长交流得知，他之前也遇到过这样的情况，原来对同一个视频提取帧的方式不同也会影响准确率，因此如果方便的话，你能上传一下您本地的nvgesture的数据集吗？不胜感激。

**Comment by zhoubenjia** [comment]
链接：https://pan.baidu.com/s/1X5EfPzcnX6c8PH5ZOtmWOA 
提取码：d593

**Comment by wwyy1234** [comment]
> 链接：https://pan.baidu.com/s/1X5EfPzcnX6c8PH5ZOtmWOA 提取码：d593

非常感谢您的耐心回复，我已经实现了您的准确率。问题在于我用了全部的图片，造成了样本不均衡，即环境信息过多，干扰了手势的检测，再次感谢您这一个月以来对我问题的耐心解答！
