### ISSUE TITLE
您好，我在输入tools/fusion.py config/NTU.yml命令时，为什么显示 utils模块未导入呢？

### ISSUE THREAD

**Issue by L666888999** [damo-cv/MotionRGBD#7]
您好，我在输入tools/fusion.py config/NTU.yml命令时，为什么显示 utils模块未导入呢？

**Comment by zhoubenjia** [comment]
请问是否已解决？能否把报错内容贴出来共享一下？

**Comment by zhoubenjia** [comment]
> 您好，我在输入tools/fusion.py config/NTU.yml命令时，为什么显示 utils模块未导入呢？

请问是否已解决？能否把报错内容贴出来共享一下？
