### ISSUE TITLE
NTU数据集

### ISSUE THREAD

**Issue by JHang2020** [damo-cv/MotionRGBD#8]
您好，感谢您出色的工作。
请问您可以上传一份NTU处理好的数据集吗，我这里没有depth数据，所以没有办法进行预处理。

万分感谢！期待您的回复。

**Comment by zhoubenjia** [comment]
> 您好，感谢您出色的工作。 请问您可以上传一份NTU处理好的数据集吗，我这里没有depth数据，所以没有办法进行预处理。
> 
> 万分感谢！期待您的回复。

亲爱的读者朋友：
非常感谢对我们工作的关注，我们之后会把预处理好的NTU-RGBD数据上传到Google 云盘，请随时关注~

**Comment by zhoubenjia** [comment]
> 您好，感谢您出色的工作。 请问您可以上传一份NTU处理好的数据集吗，我这里没有depth数据，所以没有办法进行预处理。
> 
> 万分感谢！期待您的回复。

https://drive.google.com/drive/folders/1oBVU6mygFFD2Yyl7yB7BegRoSMFkT7Hf?usp=sharing 
请问能否提供一下Google邮箱，我开权限给你。

**Comment by zhoubenjia** [comment]
> 您好，感谢您出色的工作。 请问您可以上传一份NTU处理好的数据集吗，我这里没有depth数据，所以没有办法进行预处理。
> 
> 万分感谢！期待您的回复。

请给我一个你的邮箱，我把下载链接私发给你！

**Comment by Roywangj** [comment]
你好 @zhoubenjia @JHang2020 请问可以共享一份NTU处理好的数据集吗，感谢你们！

**Comment by zhoubenjia** [comment]
https://drive.google.com/file/d/1hWewBVqkbJlSWcrmGynw0oT6byYCFcDa/view?usp=drive_link 
仅限于研究用，用于商业目的可能会侵权！！！











在 2024-08-10 16:40:33，"Jie Wang" ***@***.***> 写道：

你好 @***@***.*** 请问可以共享一份NTU处理好的数据集吗，感谢你们！
